server.port=8081

# Configuration MySQL (Base de données user_db)
spring.datasource.url=jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configuration Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Configuration RSA (Clés de sécurité pour les tokens JWT)
jwt.rsa.public-key=classpath:public.pem
jwt.rsa.private-key=classpath:private.pem
